// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwdsmhieiexvtpiyvjpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3ZHNtaGllaWV4dnRwaXl2anB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2ODE5NzAsImV4cCI6MjA2MDI1Nzk3MH0.zVU52kgfpjdFsMjIEloyyAXVAueolLJlClYAiGmf2g4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);